.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OCI_SYSTEMD_HOOK" "1" "November 2015" "" ""
.
.SH "NAME"
\fBoci_systemd_hook\fR \- OCI systemd hook
.
.SH "SYNOPSIS"
\fBoci_systemd_hook\fR [prestart|poststop]
.
.SH "DESCRIPTION"
Setup environment for systemd to run in docker or a OCI compatible runtime\. It is expected to receive the state of the container including the pid and ID over stdin as defined in the OCI specification (https://github\.com/opencontainers/specs)\. It mounts tmpfs at /run and /tmp, links journal directory to the host using a bind mount and creates /etc/machine\-id for the container systemd\.
.
.SH "ARGUMENTS"
.
.IP "\(bu" 4
prestart Setup the systemd environment in a container
.
.IP "\(bu" 4
poststop Teardown and undo the changes on the host done during prestart
.
.IP "" 0
.
.SH "AUTHORS"
Mrunal Patel \fImrunalp@gmail\.com\fR Dan Walsh \fIdwalsh@redhat\.com\fR
